Temporarily fix the disk resize for fc41

diff --git a/kvm-install-vm b/kvm-install-vm
--- a/kvm-install-vm
+++ b/kvm-install-vm
@@ -682,11 +682,13 @@ _EOF_
 				die "Could not resize disk."
 			;;
 		*)
-			qemu-img create -f qcow2 \
-				-o preallocation=metadata $DISK.new $DISK_SIZE &>>${VMNAME}.log &&
-				virt-resize --quiet --expand /dev/sda1 $DISK $DISK.new &>>${VMNAME}.log &&
-				(mv $DISK.new $DISK && ok) ||
-				die "Could not resize disk."
+			set -ex
+			partition=/dev/sda4 # This was sda1 initially (see: virt-filesystems -a img.qcow2 --all --long)
+			# TODO: Make ^ conditional so it still uses sda1 for ext4 based quest images
+			qemu-img create -f qcow2 -o preallocation=metadata $DISK.new $DISK_SIZE &>>${VMNAME}.log
+			virt-resize --quiet --expand $partition $DISK $DISK.new &>>${VMNAME}.log
+			(mv $DISK.new $DISK && ok) || die "Could not resize disk."
+			set +ex
 			;;
 		esac
 	fi
